//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodForLife.Data.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FeedforlifeEntities : DbContext
    {
        public FeedforlifeEntities()
            : base("name=FeedforlifeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mtblPartyType> mtblPartyTypes { get; set; }
        public virtual DbSet<mtblRole> mtblRoles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblDonorRequestVendor> tblDonorRequestVendors { get; set; }
        public virtual DbSet<tbluser> tblusers { get; set; }
        public virtual DbSet<tblusersRole> tblusersRoles { get; set; }
        public virtual DbSet<tblVendor> tblVendors { get; set; }
        public virtual DbSet<tblAdminTerritory> tblAdminTerritories { get; set; }
        public virtual DbSet<tblDonorRequest> tblDonorRequests { get; set; }
    
        public virtual int USP_SaveDonationDetails(string donorName, string contactNumber, string emailId, Nullable<System.DateTime> dOB, Nullable<System.DateTime> weddingAnniversary, string eventName, Nullable<System.DateTime> eventDate, string eventAddress, string city, string state, string pinCode, Nullable<long> partyTypeId, string foodType, Nullable<int> totalServingsInvited, Nullable<System.TimeSpan> collectionTime, Nullable<int> totalServingsLeft, string requestStatus, Nullable<long> primaryAdminId)
        {
            var donorNameParameter = donorName != null ?
                new ObjectParameter("DonorName", donorName) :
                new ObjectParameter("DonorName", typeof(string));
    
            var contactNumberParameter = contactNumber != null ?
                new ObjectParameter("ContactNumber", contactNumber) :
                new ObjectParameter("ContactNumber", typeof(string));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var weddingAnniversaryParameter = weddingAnniversary.HasValue ?
                new ObjectParameter("WeddingAnniversary", weddingAnniversary) :
                new ObjectParameter("WeddingAnniversary", typeof(System.DateTime));
    
            var eventNameParameter = eventName != null ?
                new ObjectParameter("EventName", eventName) :
                new ObjectParameter("EventName", typeof(string));
    
            var eventDateParameter = eventDate.HasValue ?
                new ObjectParameter("EventDate", eventDate) :
                new ObjectParameter("EventDate", typeof(System.DateTime));
    
            var eventAddressParameter = eventAddress != null ?
                new ObjectParameter("EventAddress", eventAddress) :
                new ObjectParameter("EventAddress", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            var pinCodeParameter = pinCode != null ?
                new ObjectParameter("PinCode", pinCode) :
                new ObjectParameter("PinCode", typeof(string));
    
            var partyTypeIdParameter = partyTypeId.HasValue ?
                new ObjectParameter("PartyTypeId", partyTypeId) :
                new ObjectParameter("PartyTypeId", typeof(long));
    
            var foodTypeParameter = foodType != null ?
                new ObjectParameter("FoodType", foodType) :
                new ObjectParameter("FoodType", typeof(string));
    
            var totalServingsInvitedParameter = totalServingsInvited.HasValue ?
                new ObjectParameter("TotalServingsInvited", totalServingsInvited) :
                new ObjectParameter("TotalServingsInvited", typeof(int));
    
            var collectionTimeParameter = collectionTime.HasValue ?
                new ObjectParameter("CollectionTime", collectionTime) :
                new ObjectParameter("CollectionTime", typeof(System.TimeSpan));
    
            var totalServingsLeftParameter = totalServingsLeft.HasValue ?
                new ObjectParameter("TotalServingsLeft", totalServingsLeft) :
                new ObjectParameter("TotalServingsLeft", typeof(int));
    
            var requestStatusParameter = requestStatus != null ?
                new ObjectParameter("RequestStatus", requestStatus) :
                new ObjectParameter("RequestStatus", typeof(string));
    
            var primaryAdminIdParameter = primaryAdminId.HasValue ?
                new ObjectParameter("PrimaryAdminId", primaryAdminId) :
                new ObjectParameter("PrimaryAdminId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_SaveDonationDetails", donorNameParameter, contactNumberParameter, emailIdParameter, dOBParameter, weddingAnniversaryParameter, eventNameParameter, eventDateParameter, eventAddressParameter, cityParameter, stateParameter, pinCodeParameter, partyTypeIdParameter, foodTypeParameter, totalServingsInvitedParameter, collectionTimeParameter, totalServingsLeftParameter, requestStatusParameter, primaryAdminIdParameter);
        }
    }
}
