//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodForLife.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDonorRequestVendor
    {
        public long Id { get; set; }
        public Nullable<long> RequestId { get; set; }
        public Nullable<long> VendorId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Createddate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public long NGoId { get; set; }
    
        public virtual tblDonorRequest tblDonorRequest { get; set; }
        public virtual tblDonorRequest tblDonorRequest1 { get; set; }
        public virtual tblNGO tblNGO { get; set; }
    }
}
