//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodForLife.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVendor()
        {
            this.tblDonorRequestVendors = new HashSet<tblDonorRequestVendor>();
            this.tblDonorRequestVendors1 = new HashSet<tblDonorRequestVendor>();
        }
    
        public long Id { get; set; }
        public string VendorName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address_Primary { get; set; }
        public string Address_Secondary { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Createddate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDonorRequestVendor> tblDonorRequestVendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDonorRequestVendor> tblDonorRequestVendors1 { get; set; }
    }
}
